import java.util.Scanner;
    public class Questão06{
        public static void main(String[]args){
            Scanner Calcular = new scanner (System.in);
            String Quantidade; Int Numero;
            System.out.println("Numero:  ");
            Numero = Calcular.nextInt();
            Quantidade = Integer.toString(Numero);
            System.out.printf("Tem "+ Quantidade.lenght()+" Numeros");


        }

    }